name: Deploy Next.js App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:  # Explicitly define permissions
      contents: read  # For reading the repository contents
      packages: write  # For pushing to GitHub Container Registry (ghcr.io)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
        
    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/safe-place-frontend:latest
        
  redeploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Trigger Portainer Stack Redeploy
      run: |
        curl -X POST "$PORTAINER_WEBHOOK_URL"
      env:
        PORTAINER_WEBHOOK_URL: ${{ secrets.PORTAINER_WEBHOOK_URL }}
